### ISSUE TITLE
copyright holder

### ISSUE THREAD

**Issue by slivingston** [shaesaert/C-TuLiP#3]
Can you update [LICENSE](https://github.com/shaesaert/C-TuLiP/blob/f272faa8598dc8335e456c1cfd580ca4ebcbce05/LICENSE) to have the legal name of the copyright holder? I guess that it should be California Institute of Technology.

Compare with the [license of TuLiP](https://github.com/tulip-control/tulip-control/blob/afa152d8fa044b797f9681c7fd976a3814a59b75/LICENSE).

**Comment by shaesaert** [comment]
This has been fixed in the main branch. I assumed that I only needed to add the part for Caltech. Or should I inherit the other one too?
